# Introducing `numpy` (Numerical Python)
`numpy` or simply `np` is a popular machine learning library in Python. Almost all linear algebra data, operations, and algorithms can be programmed with the help of `np`.

## Tensors
A tensor is instantiated using `array()` method of `numpy`. In particular, we can create a column vector by supplying its elements:

In [1]:
import numpy as np
a = np.array([[1],[-1]])
b = np.array([[-1],[2],[0]])
print(a.shape)
print(b.shape)

(2, 1)
(3, 1)


We use a tensor's `shape` property to determine its dimensions. 

Technically, a vector is a column vector. So, the following are not vectors as we know in linear algebra:

In [2]:
a = np.array([1, -1])
b = np.array([-1,2,0])
print(a.shape)
print(b.shape)

(2,)
(3,)


However, computers see both of them as simply sequence of data. Loosely, both can be interpreted as vectors. We can always reshape a tensor from one dimension into another. Before discussing the `reshape` method, let us digress and discuss list and tuple.
## List and Tuple

Before going further about shapes, let us focus on list and tuples. Both represent input arguments and output results of `np` functions.
A list is surrounded by brackets `[]`. The elements can change and not necessarily unique.

In [3]:
# a list with 2 elements
a = [1,2]
print(a)
# let's add 2 elements
# using append()
a.append(3)
# using + operator
a += [4]
print(a)

[1, 2]
[1, 2, 3, 4]


Instead of list, `np` can also use tuples. A tuple is like a list except that it is enclosed in `()`. The elements are fixed after a list has been created. 

In [4]:
# a tuple with 2 elements
a = (1,2)
print(a)
# this is an error since a tuple can not be changed after initialization
a.append(3)
a += (3)

(1, 2)


AttributeError: 'tuple' object has no attribute 'append'

`np` accepts both list and tuple as arguments.

In [5]:
# list to np tensor
print(np.array([1,-1]))
# tuple to np tensor
print(np.array((1,-1)))

[ 1 -1]
[ 1 -1]


## Tensor Shape

As mentioned earlier, we can use `reshape()` function to reshape a tensor into a column vector:

In [6]:
a = np.array([1, -1])
b = np.array([-1,2,0])
a = np.reshape(a,[-1,1])
b = np.reshape(b,[-1,1])
print(a.shape)
print(b.shape)

(2, 1)
(3, 1)


The use of `-1` value means let `np` figure out the other dimension given that the last dimension must be `1`.
Let us generate a tensor with `16` random integers from `-10` to `10`: 

In [7]:
a = np.random.randint(-10,10,(16,))
print(a)
print(a.shape)

[  9   0   9  -8  -1  -2  -8 -10   6   2   9  -8   4   5  -5   4]
(16,)


Let's reshape `a` as `[16,1]`, `[1,16]`, `[4,4]`, `[2,2,4]`. To minimize the repetition of code, let us build a reusable function for reshaping tensors and use it to reshape our `(16,)` tensor into the target shape.

In [8]:
def tensor_shaper(a, shape):
  a = np.reshape(a, shape)
  print(a)
  print(a.shape)

tensor_shaper(a,[16,1])
tensor_shaper(a,[1,16])
tensor_shaper(a,[4,4])
tensor_shaper(a,[2,2,4])

[[  9]
 [  0]
 [  9]
 [ -8]
 [ -1]
 [ -2]
 [ -8]
 [-10]
 [  6]
 [  2]
 [  9]
 [ -8]
 [  4]
 [  5]
 [ -5]
 [  4]]
(16, 1)
[[  9   0   9  -8  -1  -2  -8 -10   6   2   9  -8   4   5  -5   4]]
(1, 16)
[[  9   0   9  -8]
 [ -1  -2  -8 -10]
 [  6   2   9  -8]
 [  4   5  -5   4]]
(4, 4)
[[[  9   0   9  -8]
  [ -1  -2  -8 -10]]

 [[  6   2   9  -8]
  [  4   5  -5   4]]]
(2, 2, 4)


## Tensor Operations

`numpy` supports various tensor operations.

For example: tensor addition

In [9]:
a = np.random.randint(-4,4,(2,2))
b = np.random.randint(-4,4,(2,2))
print(a, ": a")
print(b, ": b")
# using + operator
print(a+b, ": a+b")
# alternatively using add() method
print(np.add(a,b), ": a+b")

[[-2 -4]
 [ 0 -4]] : a
[[ 3 -2]
 [ 2 -1]] : b
[[ 1 -6]
 [ 2 -5]] : a+b
[[ 1 -6]
 [ 2 -5]] : a+b


Other examples: subtraction, multiplication, division

In [ ]:
a = np.random.randint(-4,4,(2,2))
b = np.random.randint(-4,4,(2,2))
print(a, ": a")
print(b, ": b")
# using - operator
print(a-b, ": a-b")
# alternatively using subtract() method
print(np.subtract(a,b), ": a-b")

# using * operator (Hadamard Product or element-wise multiply)
print(a*b, ": a*b")
# alternatively using multiply() method
print(np.multiply(a,b), ": a*b = Hadamard product")

# matrix multiply as we know it in linear algebra
print(np.matmul(a,b), ": a*b = linear algebra mul")

if b.all():
    print(a/b, ": a/b")
    # alternatively using divide() method
    print(np.divide(a,b), ": a/b")
else:
    print("Divide by zero is not defined.")

Note that the multiply method is an element-wise multiplication (Hadamard product) not matrix multiplication. If we want matrix multiplication, we shoud use `matmul()` method.

In [ ]:
print(np.matmul(a,b), ": a matmul b")

## Vector Operation
In machine learning, dot product is a common vector operation. For example, it is used to the measure similarity between 2 vectors. In `np`, we use `dot()` method to execute a dot product.

In [ ]:
a = np.array([1,2,-1])
a = np.reshape(a, (1,-1))
b = np.array([1,2,1])
b = np.reshape(b, (-1,1))

# equiv to inner product 1 x 3 dot 3 x 1 = 1 x 1
c = np.dot(a,b)
print(a, ": a")
print(b, ": b")
print(c, ": a dot b")



## Other Tensor Operations
Transpose, trace, diagonal elements, inverse (if square and non-singular).
Transpose:

In [10]:
a = np.random.randint(-3,3,(4,4))
print(a)

[[ 0 -2 -2 -2]
 [ 1 -1 -1 -3]
 [-3  2  0 -1]
 [ 2  0  0  0]]


In [11]:
print(a.T)

[[ 0  1 -3  2]
 [-2 -1  2  0]
 [-2 -1  0  0]
 [-2 -3 -1  0]]


In [12]:
print(np.trace(a))

-1


In [13]:
print(np.diagonal(a))

[ 0 -1  0  0]


In [14]:
print(np.linalg.inv(a))

[[-7.40148683e-17 -0.00000000e+00 -0.00000000e+00  5.00000000e-01]
 [ 1.25000000e-01 -2.50000000e-01  5.00000000e-01  8.75000000e-01]
 [-8.75000000e-01  7.50000000e-01 -5.00000000e-01 -1.12500000e+00]
 [ 2.50000000e-01 -5.00000000e-01 -0.00000000e+00  2.50000000e-01]]


## Data Types

For convenience, we have used `int` elements. In machine learning, tensors are generally floating point datatypes. Exceptions are in quantized models used in resource constrained computers. Here are some examples of tensors of the same numerical value but with different precision:

In [15]:
a = np.array([1, 2], np.int)
print(a, " :a")
print("a.dtype", a.dtype)

b = np.array([1, 2], np.float32)
print(b, " :b")
print("b.dtype", b.dtype)

# np can figure out the data type from initial values
c = np.array([1., 2.])
print(c, " :c")
print("c.dtype", c.dtype)

[1 2]  :a
a.dtype int64
[1. 2.]  :b
b.dtype float32
[1. 2.]  :c
c.dtype float64


## Special Tensors
`np` has methods to instantiate special tensors
For example, tensor of ones and zeros:

In [16]:
a = np.ones([3,3])
print(a)
b = np.zeros([3,3])
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Diagonal tensor:

In [17]:
a = np.diag(np.ones((3,)))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


The above example creates an identity matrix. We can create the same identity matrix using `identity` method:


In [18]:
# 3 x 3 identity matrix
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Axis
Every tensor has dimensions. As such, `np` supports operations with respect to a specific dimension. 
For example, given a `4x5` tensor with random integer elements, let us compute the `sum` per row (ie along `axis=1`) or per column (ie along `axis=0`):

In [19]:
a = np.random.randint(-3,3,(4,5))
print(a)
row_max = np.sum(a, axis=1)
print(row_max)

[[-3  0  1 -1  0]
 [-1 -1 -2  2  2]
 [-3  1 -3 -1  0]
 [-1 -1 -1  2 -2]]
[-3  0 -6 -3]


In [20]:
row_col = np.sum(a, axis=0)
print(row_col)

[-8 -1 -5  2  0]


We can also get the sum of all elemennts:

In [21]:
print(np.sum(a))

-12


## Other Common Functions
Maximum element in a tensor:

In [22]:
a = np.random.randint(-10,10,(4,5))
print(a)
print(np.amax(a))

[[-1 -8 -5 -9  8]
 [ 3 -6 -1  2 -6]
 [ 2 -5 -3 -9 -8]
 [-5 -9 -6 -9  2]]
8


Minimum element in a tensor:

In [23]:
print(np.amin(a))

-9


Absolute value, squared, etc:

In [24]:
print(np.abs(a))

[[1 8 5 9 8]
 [3 6 1 2 6]
 [2 5 3 9 8]
 [5 9 6 9 2]]


In [25]:
print(a**2)

[[ 1 64 25 81 64]
 [ 9 36  1  4 36]
 [ 4 25  9 81 64]
 [25 81 36 81  4]]


Square root of absolute value:

In [26]:
print(np.sqrt(np.abs(a)))

[[1.         2.82842712 2.23606798 3.         2.82842712]
 [1.73205081 2.44948974 1.         1.41421356 2.44948974]
 [1.41421356 2.23606798 1.73205081 3.         2.82842712]
 [2.23606798 3.         2.44948974 3.         1.41421356]]
